# Generated by Django 5.1.15 on 2026-10-04 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_useraddress"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="paymentproof",
            new_name="market_paym_transac_623995_idx",
            old_name="market_paym_transac_3dfc91_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="market_prod_active_9d31f3_idx",
            old_name="market_prod_active_2c2d6e_idx",
        ),
        migrations.RenameIndex(
            model_name="useraddress",
            new_name="market_user_user_id_a969ab_idx",
            old_name="market_usera_user_id_9a5c8e_idx",
        ),
    ]
