"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {Address,api,naira} from "@/lib/api";
import {CartLine,getCart,getToken,saveCart} from "@/lib/store";

type Lga={id:number;name:string;delivery_fee:number};type Pay={bank:string;number:string;name:string};
export default function Checkout(){
 const router=useRouter();const[token,setTokenState]=useState<string>();const[cart,setCart]=useState<CartLine[]>([]);const[addresses,setAddresses]=useState<Address[]>([]);const[lgas,setLgas]=useState<Lga[]>([]);const[pays,setPays]=useState<Pay[]>([]);const[selected,setSelected]=useState<number>();const[method,setMethod]=useState("cod");const[showForm,setShowForm]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 const[form,setForm]=useState({first_name:"",last_name:"",phone:"",address:"",state:"Zamfara",city:"Talata Mafara",lga:""});
 useEffect(()=>{const t=getToken();setTokenState(t);setCart(getCart());if(!t){router.replace("/login?next=/checkout");return}Promise.all([api<Address[]>("addresses/",{},t),api<Lga[]>("lgas/"),api<{accounts:Pay[]}>("payment-info/")]).then(([a,l,p])=>{setAddresses(a);setLgas(l);setPays(p.accounts);setSelected(a.find(x=>x.is_default)?.id||a[0]?.id);setForm(f=>({...f,lga:String(l.find(x=>x.name.toLowerCase().includes("talata"))?.id||l[0]?.id||"")}))}).catch(e=>setError(e.message))},[router]);
 const selectedAddress=addresses.find(x=>x.id===selected);const subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0);const fee=selectedAddress?Number(lgas.find(x=>x.id===selectedAddress.lga)?.delivery_fee||0):0;const total=Math.max(0,subtotal+fee);
 const saveAddress=async()=>{if(!token)return;setError("");try{const a=await api<Address>("addresses/",{method:"POST",body:JSON.stringify({...form,lga:Number(form.lga),is_default:addresses.length===0})},token);setAddresses([...addresses,a]);setSelected(a.id);setShowForm(false)}catch(e){setError(e instanceof Error?e.message:"Could not save address")}};
 const place=async()=>{if(!token||!selectedAddress||!cart.length)return;setBusy(true);setError("");try{const order=await api<{ref:string}>("orders/",{method:"POST",body:JSON.stringify({lga:selectedAddress.lga,address:selectedAddress.address,phone:selectedAddress.phone,method,items_in:cart.map(x=>({product:x.id,qty:x.qty}))})},token);saveCart([]);router.replace(`/orders?new=${order.ref}`)}catch(e){setError(e instanceof Error?e.message:"Checkout failed")}finally{setBusy(false)}};
 if(!token)return null;
 return <main className="page"><div className="shell"><div className="section-head"><h1 style={{fontSize:25,margin:0}}>Checkout</h1><span className="muted small">🔒 Secure order</span></div>{error&&<div className="error" style={{marginBottom:10}}>{error}</div>}<div className="checkout-layout"><div>
  <section className="panel"><div className="section-head"><h2>Delivery address</h2><button className="secondary-btn" onClick={()=>setShowForm(!showForm)}>+ Add new</button></div>
   {showForm&&<div className="form-grid" style={{marginBottom:12}}><div className="form-grid" style={{gridTemplateColumns:"1fr 1fr"}}><div className="field"><label>First name</label><input value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></div><div className="field"><label>Last name</label><input value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></div></div><div className="field"><label>Phone</label><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="+234…"/></div><div className="field"><label>Delivery address</label><textarea rows={3} value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="Street, landmark and other details"/></div><div className="form-grid" style={{gridTemplateColumns:"1fr 1fr"}}><div className="field"><label>City</label><input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></div><div className="field"><label>LGA</label><select value={form.lga} onChange={e=>setForm({...form,lga:e.target.value})}>{lgas.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div></div><button className="primary-btn" onClick={saveAddress}>Save and use</button></div>}
   {addresses.length===0&&!showForm&&<div className="empty"><p>No delivery address yet.</p><button className="primary-btn" onClick={()=>setShowForm(true)}>Add an address</button></div>}
   {addresses.map(a=><button key={a.id} className={`address-card ${selected===a.id?"selected":""}`} style={{width:"100%",textAlign:"left",background:"transparent",marginBottom:8}} onClick={()=>setSelected(a.id)}><span className="radio"/><span style={{flex:1}}><b>{a.first_name} {a.last_name}</b> <span className="muted">{a.phone}</span><br/><span className="small">{a.address}</span><br/><span className="small">{a.city}, {a.state}</span></span>{a.is_default&&<span className="small" style={{color:"var(--orange)",fontWeight:800}}>Default</span>}</button>)}
  </section>
  <section className="panel"><h2>Payment method</h2><button className={`payment-option ${method==="cod"?"selected":""}`} style={{width:"100%",background:"transparent",border:0,textAlign:"left"}} onClick={()=>setMethod("cod")}><span className="payment-logo">₦</span><span className="pay-copy"><strong>Pay on delivery</strong><span>Pay when your order arrives.</span></span><span className="checkmark"/></button><button className={`payment-option ${method==="transfer"?"selected":""}`} style={{width:"100%",background:"transparent",border:0,textAlign:"left"}} onClick={()=>setMethod("transfer")}><span className="payment-logo">🏦</span><span className="pay-copy"><strong>Bank transfer</strong><span>Transfer after placing the order; admin confirms your proof.</span></span><span className="checkmark"/></button>{method==="transfer"&&<div className="success" style={{marginTop:10}}>{pays.length?<><b>Transfer details</b>{pays.map(p=><div key={p.bank} style={{marginTop:7}}>{p.bank}: {p.number} · {p.name}</div>)}</>:"Bank transfer details will be provided after your order is created."}</div>}</section>
  <section className="panel"><h2>Items ({cart.length})</h2>{cart.map(x=><div key={x.id} className="summary-row"><span>{x.name} × {x.qty}</span><b>{naira(x.price*x.qty)}</b></div>)}</section>
 </div><aside className="panel summary"><h2 style={{marginTop:0}}>Order total</h2><div className="summary-row"><span>Subtotal</span><b>{naira(subtotal)}</b></div><div className="summary-row"><span>Delivery</span><b>{naira(fee)}</b></div><div className="summary-row summary-total"><span>Total</span><b>{naira(total)}</b></div><button className="primary-btn" disabled={!selectedAddress||busy||!cart.length} onClick={place}>{busy?"Placing order…":`Place order · ${naira(total)}`}</button><p className="muted small">Your delivery address is used only to fulfill this order.</p></aside></div></div></main>
}
